import { Node, Edge } from '@xyflow/react';

interface WorkflowData {
  nodes: Node[];
  edges: Edge[];
  agentName: string;
}

function getConnectedNodes(nodeId: string, edges: Edge[], nodes: Node[]): Node[] {
  const connectedEdges = edges.filter(e => e.source === nodeId);
  return connectedEdges.map(e => nodes.find(n => n.id === e.target)).filter(Boolean) as Node[];
}

function getNodesByType(nodes: Node[], type: string): Node[] {
  return nodes.filter(n => n.type === type);
}

export function generatePythonCode({ nodes, edges, agentName }: WorkflowData): string {
  const tools = getNodesByType(nodes, 'tool');
  const agents = getNodesByType(nodes, 'agent');
  const guardrails = getNodesByType(nodes, 'guardrail');
  const conditions = getNodesByType(nodes, 'condition');

  let code = `"""
${agentName} - Generated by Visual Agent Builder
"""

from agents import Agent, Runner, function_tool
`;

  // Add guardrail imports if needed
  if (guardrails.length > 0) {
    code += `from agents import InputGuardrail, OutputGuardrail, GuardrailFunctionOutput
`;
  }

  code += `
# ============================================
# Tools
# ============================================
`;

  // Generate tool functions
  if (tools.length > 0) {
    tools.forEach((tool, index) => {
      const toolName = (tool.data?.label as string || `tool_${index + 1}`).toLowerCase().replace(/\s+/g, '_');
      code += `
@function_tool
def ${toolName}(query: str) -> str:
    """${tool.data?.label || 'Execute tool function'}"""
    # TODO: Implement tool logic
    return f"Result for: {query}"
`;
    });
  } else {
    code += `# No tools defined
`;
  }

  // Generate guardrails
  if (guardrails.length > 0) {
    code += `
# ============================================
# Guardrails
# ============================================
`;
    guardrails.forEach((guardrail, index) => {
      const guardrailName = (guardrail.data?.label as string || `guardrail_${index + 1}`).toLowerCase().replace(/\s+/g, '_');
      code += `
async def ${guardrailName}_check(ctx, agent, input_data) -> GuardrailFunctionOutput:
    """${guardrail.data?.label || 'Validate input/output'}"""
    # TODO: Implement guardrail logic
    return GuardrailFunctionOutput(
        output_info={"validated": True},
        tripwire_triggered=False
    )

${guardrailName} = InputGuardrail(guardrail_function=${guardrailName}_check)
`;
    });
  }

  // Generate conditions as helper functions
  if (conditions.length > 0) {
    code += `
# ============================================
# Conditions
# ============================================
`;
    conditions.forEach((condition, index) => {
      const conditionName = (condition.data?.label as string || `condition_${index + 1}`).toLowerCase().replace(/\s+/g, '_');
      code += `
def check_${conditionName}(result: str) -> bool:
    """${condition.data?.label || 'Evaluate condition'}"""
    # TODO: Implement condition logic
    return True
`;
    });
  }

  code += `
# ============================================
# Agent Definition
# ============================================
`;

  // Generate agent definition
  const toolNames = tools.map((t, i) => 
    (t.data?.label as string || `tool_${i + 1}`).toLowerCase().replace(/\s+/g, '_')
  );
  const guardrailNames = guardrails.map((g, i) => 
    (g.data?.label as string || `guardrail_${i + 1}`).toLowerCase().replace(/\s+/g, '_')
  );

  const agentVarName = agentName.toLowerCase().replace(/\s+/g, '_');
  
  code += `
${agentVarName} = Agent(
    name="${agentName}",
    instructions="""You are a helpful AI assistant.
    
Your capabilities include:
${tools.map(t => `- ${t.data?.label || 'Tool'}`).join('\n') || '- General assistance'}
""",`;

  if (toolNames.length > 0) {
    code += `
    tools=[${toolNames.join(', ')}],`;
  }

  if (guardrailNames.length > 0) {
    code += `
    input_guardrails=[${guardrailNames.join(', ')}],`;
  }

  code += `
)
`;

  code += `
# ============================================
# Run the Agent
# ============================================

if __name__ == "__main__":
    user_input = input("Enter your message: ")
    result = Runner.run_sync(${agentVarName}, user_input)
    print(f"\\nAgent Response:\\n{result.final_output}")
`;

  return code;
}

export function generateTypeScriptCode({ nodes, edges, agentName }: WorkflowData): string {
  const tools = getNodesByType(nodes, 'tool');
  const agents = getNodesByType(nodes, 'agent');
  const guardrails = getNodesByType(nodes, 'guardrail');
  const conditions = getNodesByType(nodes, 'condition');

  let code = `/**
 * ${agentName} - Generated by Visual Agent Builder
 */

import { Agent, Runner, tool } from '@openai/agents';

// ============================================
// Types
// ============================================

interface ToolResult {
  success: boolean;
  data: string;
}

`;

  // Generate tool functions
  code += `// ============================================
// Tools
// ============================================
`;

  if (tools.length > 0) {
    tools.forEach((t, index) => {
      const toolName = (t.data?.label as string || `tool${index + 1}`).replace(/\s+/g, '');
      const toolNameCamel = toolName.charAt(0).toLowerCase() + toolName.slice(1);
      code += `
const ${toolNameCamel} = tool({
  name: '${toolNameCamel}',
  description: '${t.data?.label || 'Execute tool function'}',
  parameters: {
    type: 'object',
    properties: {
      query: { type: 'string', description: 'The query to process' }
    },
    required: ['query']
  },
  execute: async ({ query }): Promise<ToolResult> => {
    // TODO: Implement tool logic
    return { success: true, data: \`Result for: \${query}\` };
  }
});
`;
    });
  } else {
    code += `// No tools defined
`;
  }

  // Generate guardrails
  if (guardrails.length > 0) {
    code += `
// ============================================
// Guardrails
// ============================================
`;
    guardrails.forEach((guardrail, index) => {
      const guardrailName = (guardrail.data?.label as string || `guardrail${index + 1}`).replace(/\s+/g, '');
      const guardrailNameCamel = guardrailName.charAt(0).toLowerCase() + guardrailName.slice(1);
      code += `
const ${guardrailNameCamel} = {
  name: '${guardrailNameCamel}',
  validate: async (input: string): Promise<{ valid: boolean; reason?: string }> => {
    // TODO: Implement guardrail logic
    return { valid: true };
  }
};
`;
    });
  }

  // Generate conditions
  if (conditions.length > 0) {
    code += `
// ============================================
// Conditions
// ============================================
`;
    conditions.forEach((condition, index) => {
      const conditionName = (condition.data?.label as string || `condition${index + 1}`).replace(/\s+/g, '');
      const conditionNameCamel = 'check' + conditionName.charAt(0).toUpperCase() + conditionName.slice(1);
      code += `
const ${conditionNameCamel} = (result: string): boolean => {
  // TODO: Implement condition logic
  return true;
};
`;
    });
  }

  code += `
// ============================================
// Agent Definition
// ============================================
`;

  const toolNames = tools.map((t, i) => {
    const name = (t.data?.label as string || `tool${i + 1}`).replace(/\s+/g, '');
    return name.charAt(0).toLowerCase() + name.slice(1);
  });

  const agentVarName = agentName.replace(/\s+/g, '');
  const agentVarNameCamel = agentVarName.charAt(0).toLowerCase() + agentVarName.slice(1);

  code += `
const ${agentVarNameCamel} = new Agent({
  name: '${agentName}',
  instructions: \`You are a helpful AI assistant.
    
Your capabilities include:
${tools.map(t => `- ${t.data?.label || 'Tool'}`).join('\n') || '- General assistance'}
\`,`;

  if (toolNames.length > 0) {
    code += `
  tools: [${toolNames.join(', ')}],`;
  }

  code += `
});
`;

  code += `
// ============================================
// Run the Agent
// ============================================

async function main() {
  const userInput = 'Hello, how can you help me?';
  
  const result = await Runner.run(${agentVarNameCamel}, userInput);
  console.log('\\nAgent Response:');
  console.log(result.finalOutput);
}

main().catch(console.error);
`;

  return code;
}
